import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { useAccount } from "wagmi";
import JellyBotsChecker from "../components/JellyBotsChecker";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { address } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ConnectButton showBalance={false} chainStatus="none" />
        {address && <JellyBotsChecker address={address} />}
      </main>
    </div>
  );
};

export default Home;
